[package]
name = "xrpl_cli"
description = "A CLI for the XRP Ledger"
version = "0.11.0"
license = "Apache-2.0"
repository = "https://github.com/gmosx/xrpl_sdk_rust/tree/main/xrpl_sdk_jsonrpc"
keywords = ["xrpl", "ledger", "cli"]
authors = ["George Moschovitis <gmosx@reizu.org>"]
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = "0.1"
tracing-subscriber = "0.3"
hex = "0.4"
xrpl_binary_codec = { path = "../xrpl_binary_codec", version = "0.11" }
xrpl_types = { path = "../xrpl_types", version = "0.11" }
xrpl_sdk_jsonrpc = { path = "../xrpl_sdk_jsonrpc", version = "0.11" }

[[bin]]
name = "xrpl"
path = "src/main.rs"
